name: Build Windows Exe
on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    
    steps:
      - uses: actions/checkout@v4

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Retarget and Build Solution
        # Adicionei o parâmetro /p:TreatWarningsAsErrors=false para ignorar o erro C2220
        run: msbuild aes-finder.sln /p:Configuration=Release /p:Platform=Win32 /p:PlatformToolset=v143 /p:WindowsTargetPlatformVersion=10.0 /p:TreatWarningsAsErrors=false

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: aes-finder-windows
          path: |
            **/Release/aes-finder.exe
            **/Win32/Release/aes-finder.exe
